language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install: pip install . -rtest/requirements.txt
script: python manage.py test
deploy:
  on:
    branch: master
  provider: pypi
  distributions: sdist bdist_wheel
  user: efl_phx
