language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install: pip install . -rtest/requirements.txt
script: python manage.py test
deploy:
  on:
    branch: master
  provider: pypi
  distributions: sdist bdist_wheel
  user: efl_phx
  password:
    secure: wuAos26NLH8PNs0J9sWfWZ2JlTDPpPAoVwM6i8UJ4WhPLJiyEZPtC9UB8jOZx0NuVTD3JkW8x1cVGJz28YfVjDGGxQbkahn0PRnEGDngkgABeHoXSoayfVMYAne7EHRBqetvIkNhUfCpFTmlXuALIja1kMSgrHmevth6a8DKI5uwvvGorwWfcz5Un3+EHmf675M1y2rOCYTxQrQXTget6Ah5HWP0ivSR+ou3/4jQD9NAfNicoqMP8GY8b45t2iOKbnfEQX1LCjICcqLi98lCaJcfwXftCNBY4JLbL0Q1iG/VeNVvjru+i5f5TZdITEoL6iG0dOc0bXQjnscl+AtFjVU96wEHDGMBA/Vn9UtV6dvWbbntN27ZW64qi6H6ef0na/BQW+MmDvSzf5rj3XG1Yx4ON4ygppM3khRIZ8l+VNfpDki2B6t3eTorw4Gsup5B3oHibikcZ4QcwcXjeNWyGyuEo+eVxKO71NslRm5xAgYdYidl5swBcT4YOwWm3InzVA78GsbZq8Sq0E9iXHYSLzjHsq0XAg76jrmDjZN9f4xDZLuncS9y2mfhBXrajG/hvwAWt9XLdpl7qK4nEMcSRf6zSn1PLteP9imSj1fQJyNt1x5FOkGy9kiKSCI9Q6OfiSno6YpwryFRjEQQfz0h8s5+kbssy7hlSS410j2+5CU=
